include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    unrelated_type_equality_checks: true
    public_member_api_docs: false

analyzer:
  exclude:
    - lib/**/*.*.dart
    - packages/**/*.*.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # error
    unrelated_type_equality_checks: error
    missing_required_param: error
    only_throw_errors: error
    missing_return: error
    missing_enum_constant_in_switch: error
    # warn
    parameter_assignments: warning
    use_rethrow_when_possible: warning
    # ignore
    use_setters_to_change_properties: ignore
    avoid_setters_without_getters: ignore
    one_member_abstracts: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_init_to_null: ignore
    avoid_types_on_closure_parameters: ignore
    avoid_returning_null: ignore
    prefer_function_declarations_over_variables: ignore
