name: do_app
description: Create public events to practice sports with other people.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+3

flutter_native_splash:
  color: "#202233"
  image: "assets/config/splash.png"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/config/icon.png"
  web:
    generate: true
    image_path: "assets/config/icon.png"
    background_color: "#202233"
    theme_color: "#4657D5"

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  geolocator: ^9.0.1
  google_fonts: ^3.0.1
  provider: ^6.0.3
  rxdart: ^0.27.5
  geoflutterfire: ^3.0.3
  json_annotation: ^4.6.0
  google_place: ^0.4.7
  firebase_auth: ^3.6.2
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  email_validator: ^2.1.17
  beamer: ^1.5.0
  flutter_svg: ^1.1.3
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.4.0
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.4
  tinycolor2: ^2.1.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  effective_dart: ^1.3.2
  freezed: ^2.1.0+1
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  change_app_package_name: ^1.1.0
  firebase_auth_mocks: ^0.8.7
  firebase_storage_mocks: ^0.5.1
  fake_cloud_firestore: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/picture-inverted.svg
    - assets/img/picture.svg
    - assets/img/menu.svg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600
    - family: Ultra
      fonts:
        - asset: assets/fonts/Ultra/Ultra-Regular.ttf