name: do_app
description: Create public events to practice sports with other people.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  geolocator: ^9.0.1
  google_fonts: ^3.0.1
  provider: ^6.0.3
  rxdart: ^0.27.5
  geoflutterfire: ^3.0.3
  json_annotation: ^4.6.0
  google_place: ^0.4.7
  firebase_auth: ^3.6.2
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  effective_dart: ^1.3.2
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
