name: do_app
description: Create public events to practice sports with other people.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+3

flutter_native_splash:
  color: "#202233"
  image: "assets/config/splash.png"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/config/icon.png"
  web:
    generate: true
    image_path: "assets/config/icon.png"
    background_color: "#202233"
    theme_color: "#4657D5"

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  portfolio_commons:
    path: /Users/lucadillenburg/Development/Projects/AppsPortfolio/packages/portfolio_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
  portfolio_dev_commons:
    path: /Users/lucadillenburg/Development/Projects/AppsPortfolio/packages/portfolio_dev_commons

flutter:
  uses-material-design: true
  assets:
    - assets/img/picture-inverted.svg
    - assets/img/picture.svg
    - assets/img/menu.svg
  fonts:
    - family: Inter
      fonts:
        - asset: lib/fonts/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: lib/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: lib/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600
    - family: Ultra
      fonts:
        - asset: lib/fonts/Ultra/Ultra-Regular.ttf