// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJzFHVq3dhgxfwJbtfxdy_Toqz5wq2kY',
    appId: '1:638932089763:web:ae52edb19ac201ce043816',
    messagingSenderId: '638932089763',
    projectId: 'do-app-f3b5d',
    authDomain: 'do-app-f3b5d.firebaseapp.com',
    storageBucket: 'do-app-f3b5d.appspot.com',
    measurementId: 'G-X0TKHRWCVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAovKlpmIRqS7odu6Iyh__7_FFWfKLR0',
    appId: '1:638932089763:android:7d2236f8b4835fdf043816',
    messagingSenderId: '638932089763',
    projectId: 'do-app-f3b5d',
    storageBucket: 'do-app-f3b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTV-dCNdZqkm232XiReugVJrBOYVOXB1U',
    appId: '1:638932089763:ios:c32b85c09a477a8a043816',
    messagingSenderId: '638932089763',
    projectId: 'do-app-f3b5d',
    storageBucket: 'do-app-f3b5d.appspot.com',
    iosClientId: '638932089763-gkcfhumbmdcb6kr7shnpson8cn44escn.apps.googleusercontent.com',
    iosBundleId: 'com.example.doApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTV-dCNdZqkm232XiReugVJrBOYVOXB1U',
    appId: '1:638932089763:ios:c32b85c09a477a8a043816',
    messagingSenderId: '638932089763',
    projectId: 'do-app-f3b5d',
    storageBucket: 'do-app-f3b5d.appspot.com',
    iosClientId: '638932089763-gkcfhumbmdcb6kr7shnpson8cn44escn.apps.googleusercontent.com',
    iosBundleId: 'com.example.doApp',
  );
}
